version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-20.04  
  tools:
    python: "3.11"   

python:
  install:
    - requirements: docs/doc_requirements.txt

build:
  apt_packages:
    - curl
  commands:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - pip install -r docs/doc_requirements.txt